services:
  squiddb:
    image: postgres:15.14
    container_name: squid-db
    restart: "no"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  squidstatistic:
    image: squid/squidstatistic:0.1
    container_name: squid-statistic
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - squiddb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://squiddb:5432/squid
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
volumes:
  postgres_data: