services:
  appdb:
    image: postgres:15.6-bookworm
    container_name: squiddb
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  squidstatistic:
    image: squid/squidstatistic:0.1
    container_name: squidstatistic
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: "no"
    depends_on:
      - appdb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://appdb:5432/squid
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
volumes:
  postgres_data: