--
-- DROP TABLE public."access";

CREATE TABLE public."access" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	node_id int2 NULL,
	"date" date NULL,
	datetime timestamp NULL,
	duration int4 NULL,
	client_address inet NULL,
	result_code_id int2 NULL,
	result_code_val int2 NULL,
	"size" int8 NULL,
	request_method_id int2 NULL,
	url_name varchar NULL,
	url_port int4 NULL,
	url_domain_id int4 NULL,
	"user" varchar NULL,
	hierarchy_code_id int2 NULL,
	hierarchy_code_val varchar NULL,
	type_id int2 NULL,
	CONSTRAINT access_pk PRIMARY KEY (id)
);
CREATE INDEX access_date_idx ON public.access USING btree (date);

--
-- DROP TABLE public.content_type;

CREATE TABLE public.content_type (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	CONSTRAINT content_type_pk PRIMARY KEY (id),
);
CREATE UNIQUE INDEX content_type_name_idx ON public.content_type USING btree (name);

--
-- DROP TABLE public."domain";

CREATE TABLE public."domain" (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar NULL,
	CONSTRAINT domain_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX domain_name_idx ON public.domain USING btree (name);

--
-- DROP TABLE public.hierarchy_code;

CREATE TABLE public.hierarchy_code (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	CONSTRAINT hierarchy_code_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX hierarchy_code_name_idx ON public.hierarchy_code USING btree (name);


--
-- DROP TABLE public.lastupdate;

CREATE TABLE public.lastupdate (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	node int2 NULL,
	date_update timestamp NULL,
	size_file int8 NULL,
	add_row int4 NULL,
	duration int4 NULL,
	CONSTRAINT lastupdate_pk PRIMARY KEY (id)
);


--
-- DROP TABLE public.node;

CREATE TABLE public.node (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	CONSTRAINT node_pk PRIMARY KEY (id)
);


--
-- DROP TABLE public.request_method;

CREATE TABLE public.request_method (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	CONSTRAINT request_method_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX request_method_name_idx ON public.request_method USING btree (name);


--
-- DROP TABLE public.result_code;

CREATE TABLE public.result_code (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	CONSTRAINT result_code_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX result_code_name_idx ON public.result_code USING btree (name);